[project]
name = "python-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "agent-framework>=1.0.0b251114",
    "azure-cognitiveservices-speech>=1.47.0",
    "dotenv>=0.9.9",
]
